# Exploring Tree Data Analysis

In [1]:
import pandas as pd
import altair as alt

/Users/gracelynnewest/.pyenv/versions/3.8.5/envs/berkeley_tree_data-3.8.5/lib/python3.8/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [2]:
pd.set_option('display.max_columns', None)

## Importing Tree Data


In [3]:
berkeley_trees = pd.read_csv('berkeley_trees_with_zip.csv', dtype={'ZIP': object})

In [4]:
berkeley_trees.head()

areaid                  species    strt_nam  dbh_in    block_on  spacesize  \
0       3        Prunus cerasifera  COLUSA AVE    13.0  BEVERLY PL        3.5   
1       3  Liquidambar styraciflua  COLUSA AVE     7.5  BEVERLY PL        3.5   
2       3            Planting Site  BEVERLY PL     0.0  BEVERLY PL        3.5   
3       3            Planting Site  BEVERLY PL     0.0  BEVERLY PL        3.5   
4       3            Acer  species  BEVERLY PL     1.0  BEVERLY PL        3.5   

  grate lvwires trnk hvwires location   latitude  obstree_he icon_type  \
0   NaN       Y    N       Y     LEFT  37.884954         2.0         T   
1   NaN       Y    N       Y     LEFT  37.884965         3.0         T   
2   NaN       Y    N       Y    FRONT  37.884892         NaN         P   
3   NaN       Y    N       Y    FRONT  37.884873         NaN         P   
4   NaN       Y    N       Y    FRONT  37.884855         3.0         T   

  stake_rmv  spread_ft  p_strip_wi  hvwirht                   gps_date  \
0       NaN       18.0         4.0     40.0  2012-10-01T07:00:00+00:00   
1       NaN       24.0         4.0     40.0  2012-10-01T07:00:00+00:00   
2       NaN        NaN         4.0     40.0  2012-10-01T07:00:00+00:00   
3       NaN        NaN         4.0     40.0  2012-10-01T07:00:00+00:00   
4       NaN        6.0         4.0     40.0  2012-10-01T07:00:00+00:00   

       growspace  height_ft   common_nam  stem_num   longitude  vert_prec  \
0      TREE LAWN       30.0  Cherry plum       1.0 -122.278251        0.1   
1      TREE LAWN       35.0     Sweetgum       1.0 -122.278166        0.5   
2  PLANTING SITE        NaN          NaN       NaN -122.278032        0.1   
3  PLANTING SITE        NaN          NaN       NaN -122.277953        0.1   
4      TREE LAWN       10.0        Maple       1.0 -122.277879        0.1   

   horz_prec rootb  condition monosdw   siteid  swk_width other_tree  \
0        0.1     N       20.0       N  19143.0        6.0        NaN   
1        0.4     N       60.0       N  19144.0        6.0        NaN   
2        0.1     N        NaN       N  19145.0        6.0        NaN   
3        0.1     N        NaN       N  19146.0        6.0        NaN   
4        0.1     N       60.0       N  19147.0        6.0        NaN   

                                                note  obstree_st  \
0       in decline, deadwood, suckers, included bark         1.0   
1  topped, crowded, sidewalk & road clearance, in...         2.0   
2                                                NaN         NaN   
3                                                NaN         NaN   
4                                 next to power pole         3.0   

             treesize guard strt_assig  low_tree_w itree  strt_num curb  \
0                 NaN     N          N         NaN  PRCE    1161.0    Y   
1                 NaN     N          N         NaN  LIST    1161.0    Y   
2  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN    1708.0    Y   
3  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN    1708.0    Y   
4                 NaN     N          N         NaN    AC    1712.0    Y   

                                       geometry    ZIP  
0   POINT (-122.2782510397073 37.8849535051094)  94707  
1  POINT (-122.2781663588789 37.88496491806563)  94707  
2  POINT (-122.2780324559747 37.88489176163965)  94707  
3    POINT (-122.2779527961387 37.884872693418)  94707  
4   POINT (-122.277878585939 37.88485523628039)  94707

In [5]:
berkeley_trees.tail()

areaid                  species         strt_nam  dbh_in  \
46032       7  Liriodendron tulipifera  M L KING JR WAY    16.0   
46033       7  Liriodendron tulipifera   UNIVERSITY AVE    15.0   
46034       7            Planting Site   UNIVERSITY AVE     0.0   
46035       7  Liriodendron tulipifera   UNIVERSITY AVE    16.0   
46036       7  Liriodendron tulipifera   UNIVERSITY AVE    14.0   

              block_on  spacesize grate lvwires trnk hvwires location  \
46032  M L KING JR WAY        4.0   NaN       N    N       N    FRONT   
46033   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   
46034   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   
46035   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   
46036   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   

        latitude  obstree_he icon_type stake_rmv  spread_ft  p_strip_wi  \
46032  37.871332         3.0         T       NaN       21.0         NaN   
46033  37.871171         3.0         T       NaN       21.0         NaN   
46034  37.871238         NaN         P       NaN        NaN         NaN   
46035  37.871154         3.0         T       NaN       27.0         NaN   
46036  37.871134         3.0         T       NaN       24.0         NaN   

       hvwirht                   gps_date      growspace  height_ft  \
46032      NaN  2012-12-06T08:00:00+00:00           WELL       50.0   
46033      NaN  2012-12-06T08:00:00+00:00           WELL       50.0   
46034      NaN  2012-12-06T08:00:00+00:00  PLANTING SITE        NaN   
46035      NaN  2012-12-06T08:00:00+00:00           WELL       55.0   
46036      NaN  2012-12-06T08:00:00+00:00           WELL       35.0   

       common_nam  stem_num   longitude  vert_prec  horz_prec rootb  \
46032  Tulip tree       1.0 -122.274227        0.1        0.1     N   
46033  Tulip tree       1.0 -122.274430        0.1        0.1     N   
46034         NaN       NaN -122.274688        1.3        0.7     N   
46035  Tulip tree       1.0 -122.274784        0.2        0.1     N   
46036  Tulip tree       1.0 -122.274955        0.2        0.1     N   

       condition monosdw   siteid  swk_width other_tree  \
46032       60.0       Y  33284.0        9.0        NaN   
46033       60.0       Y  33285.0        9.0        NaN   
46034        NaN       Y  33286.0        9.0        NaN   
46035       60.0       Y  33287.0        9.0        NaN   
46036       60.0       Y  33288.0        9.0        NaN   

                                                    note  obstree_st  \
46032  large trunk wound, suckers, building clearance...         3.0   
46033  branch failure, suckers, trunk tape, sooty mol...         3.0   
46034                                                NaN         NaN   
46035  between utilities, trunk tape, sooty mold, suc...         3.0   
46036  next to utility, sooty mold, suckers, trunk ta...         3.0   

                 treesize guard strt_assig  low_tree_w itree  strt_num curb  \
46032                 NaN     N          N         NaN  LITU    1820.0    N   
46033                 NaN     N          N         NaN  LITU    1814.0    N   
46034  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN    1810.0    N   
46035                 NaN     N          N         NaN  LITU    1808.0    N   
46036                 NaN     N          N         NaN  LITU    1800.0    N   

                                           geometry    ZIP  
46032  POINT (-122.2742270581849 37.87133206051946)  94703  
46033  POINT (-122.2744295618609 37.87117125868647)  94703  
46034  POINT (-122.2746875805808 37.87123767665735)  94703  
46035  POINT (-122.2747840760346 37.87115416164091)  94703  
46036  POINT (-122.2749554349902 37.87113427284294)  94703

In [6]:
berkeley_trees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46037 entries, 0 to 46036
Data columns (total 43 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   areaid      46037 non-null  int64  
 1   species     46037 non-null  object 
 2   strt_nam    46037 non-null  object 
 3   dbh_in      44851 non-null  float64
 4   block_on    43257 non-null  object 
 5   spacesize   41608 non-null  float64
 6   grate       711 non-null    object 
 7   lvwires     46037 non-null  object 
 8   trnk        45311 non-null  object 
 9   hvwires     46037 non-null  object 
 10  location    46025 non-null  object 
 11  latitude    46037 non-null  float64
 12  obstree_he  35104 non-null  float64
 13  icon_type   46037 non-null  object 
 14  stake_rmv   3259 non-null   object 
 15  spread_ft   34801 non-null  float64
 16  p_strip_wi  31361 non-null  float64
 17  hvwirht     15686 non-null  float64
 18  gps_date    46037 non-null  object 
 19  growspace   46037 non-nul

### Creating ID Column

In [7]:
# create id column
berkeley_trees = berkeley_trees.reset_index()

The reason why we want to create an index column is that it helps identify each row and if we need to call on a certain row, we can use the index number.

In [8]:
berkeley_trees.head()

index  areaid                  species    strt_nam  dbh_in    block_on  \
0      0       3        Prunus cerasifera  COLUSA AVE    13.0  BEVERLY PL   
1      1       3  Liquidambar styraciflua  COLUSA AVE     7.5  BEVERLY PL   
2      2       3            Planting Site  BEVERLY PL     0.0  BEVERLY PL   
3      3       3            Planting Site  BEVERLY PL     0.0  BEVERLY PL   
4      4       3            Acer  species  BEVERLY PL     1.0  BEVERLY PL   

   spacesize grate lvwires trnk hvwires location   latitude  obstree_he  \
0        3.5   NaN       Y    N       Y     LEFT  37.884954         2.0   
1        3.5   NaN       Y    N       Y     LEFT  37.884965         3.0   
2        3.5   NaN       Y    N       Y    FRONT  37.884892         NaN   
3        3.5   NaN       Y    N       Y    FRONT  37.884873         NaN   
4        3.5   NaN       Y    N       Y    FRONT  37.884855         3.0   

  icon_type stake_rmv  spread_ft  p_strip_wi  hvwirht  \
0         T       NaN       18.0         4.0     40.0   
1         T       NaN       24.0         4.0     40.0   
2         P       NaN        NaN         4.0     40.0   
3         P       NaN        NaN         4.0     40.0   
4         T       NaN        6.0         4.0     40.0   

                    gps_date      growspace  height_ft   common_nam  stem_num  \
0  2012-10-01T07:00:00+00:00      TREE LAWN       30.0  Cherry plum       1.0   
1  2012-10-01T07:00:00+00:00      TREE LAWN       35.0     Sweetgum       1.0   
2  2012-10-01T07:00:00+00:00  PLANTING SITE        NaN          NaN       NaN   
3  2012-10-01T07:00:00+00:00  PLANTING SITE        NaN          NaN       NaN   
4  2012-10-01T07:00:00+00:00      TREE LAWN       10.0        Maple       1.0   

    longitude  vert_prec  horz_prec rootb  condition monosdw   siteid  \
0 -122.278251        0.1        0.1     N       20.0       N  19143.0   
1 -122.278166        0.5        0.4     N       60.0       N  19144.0   
2 -122.278032        0.1        0.1     N        NaN       N  19145.0   
3 -122.277953        0.1        0.1     N        NaN       N  19146.0   
4 -122.277879        0.1        0.1     N       60.0       N  19147.0   

   swk_width other_tree                                               note  \
0        6.0        NaN       in decline, deadwood, suckers, included bark   
1        6.0        NaN  topped, crowded, sidewalk & road clearance, in...   
2        6.0        NaN                                                NaN   
3        6.0        NaN                                                NaN   
4        6.0        NaN                                 next to power pole   

   obstree_st            treesize guard strt_assig  low_tree_w itree  \
0         1.0                 NaN     N          N         NaN  PRCE   
1         2.0                 NaN     N          N         NaN  LIST   
2         NaN  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN   
3         NaN  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN   
4         3.0                 NaN     N          N         NaN    AC   

   strt_num curb                                      geometry    ZIP  
0    1161.0    Y   POINT (-122.2782510397073 37.8849535051094)  94707  
1    1161.0    Y  POINT (-122.2781663588789 37.88496491806563)  94707  
2    1708.0    Y  POINT (-122.2780324559747 37.88489176163965)  94707  
3    1708.0    Y    POINT (-122.2779527961387 37.884872693418)  94707  
4    1712.0    Y   POINT (-122.277878585939 37.88485523628039)  94707

In [9]:
berkeley_trees.rename(columns={'index': 'id'}, inplace=True)

In [10]:
berkeley_trees.head()

id  areaid                  species    strt_nam  dbh_in    block_on  \
0   0       3        Prunus cerasifera  COLUSA AVE    13.0  BEVERLY PL   
1   1       3  Liquidambar styraciflua  COLUSA AVE     7.5  BEVERLY PL   
2   2       3            Planting Site  BEVERLY PL     0.0  BEVERLY PL   
3   3       3            Planting Site  BEVERLY PL     0.0  BEVERLY PL   
4   4       3            Acer  species  BEVERLY PL     1.0  BEVERLY PL   

   spacesize grate lvwires trnk hvwires location   latitude  obstree_he  \
0        3.5   NaN       Y    N       Y     LEFT  37.884954         2.0   
1        3.5   NaN       Y    N       Y     LEFT  37.884965         3.0   
2        3.5   NaN       Y    N       Y    FRONT  37.884892         NaN   
3        3.5   NaN       Y    N       Y    FRONT  37.884873         NaN   
4        3.5   NaN       Y    N       Y    FRONT  37.884855         3.0   

  icon_type stake_rmv  spread_ft  p_strip_wi  hvwirht  \
0         T       NaN       18.0         4.0     40.0   
1         T       NaN       24.0         4.0     40.0   
2         P       NaN        NaN         4.0     40.0   
3         P       NaN        NaN         4.0     40.0   
4         T       NaN        6.0         4.0     40.0   

                    gps_date      growspace  height_ft   common_nam  stem_num  \
0  2012-10-01T07:00:00+00:00      TREE LAWN       30.0  Cherry plum       1.0   
1  2012-10-01T07:00:00+00:00      TREE LAWN       35.0     Sweetgum       1.0   
2  2012-10-01T07:00:00+00:00  PLANTING SITE        NaN          NaN       NaN   
3  2012-10-01T07:00:00+00:00  PLANTING SITE        NaN          NaN       NaN   
4  2012-10-01T07:00:00+00:00      TREE LAWN       10.0        Maple       1.0   

    longitude  vert_prec  horz_prec rootb  condition monosdw   siteid  \
0 -122.278251        0.1        0.1     N       20.0       N  19143.0   
1 -122.278166        0.5        0.4     N       60.0       N  19144.0   
2 -122.278032        0.1        0.1     N        NaN       N  19145.0   
3 -122.277953        0.1        0.1     N        NaN       N  19146.0   
4 -122.277879        0.1        0.1     N       60.0       N  19147.0   

   swk_width other_tree                                               note  \
0        6.0        NaN       in decline, deadwood, suckers, included bark   
1        6.0        NaN  topped, crowded, sidewalk & road clearance, in...   
2        6.0        NaN                                                NaN   
3        6.0        NaN                                                NaN   
4        6.0        NaN                                 next to power pole   

   obstree_st            treesize guard strt_assig  low_tree_w itree  \
0         1.0                 NaN     N          N         NaN  PRCE   
1         2.0                 NaN     N          N         NaN  LIST   
2         NaN  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN   
3         NaN  SMALL (SDWLK 5 FT)   NaN          N         NaN   NaN   
4         3.0                 NaN     N          N         NaN    AC   

   strt_num curb                                      geometry    ZIP  
0    1161.0    Y   POINT (-122.2782510397073 37.8849535051094)  94707  
1    1161.0    Y  POINT (-122.2781663588789 37.88496491806563)  94707  
2    1708.0    Y  POINT (-122.2780324559747 37.88489176163965)  94707  
3    1708.0    Y    POINT (-122.2779527961387 37.884872693418)  94707  
4    1712.0    Y   POINT (-122.277878585939 37.88485523628039)  94707

## Get Total Trees By Zip Code


In [11]:
berkeley_trees.groupby(['ZIP']).count()

id  areaid  species  strt_nam  dbh_in  block_on  spacesize  grate  \
ZIP                                                                          
94702  7328    7328     7328      7328    6937      6956       7003     36   
94703  8241    8241     8241      8241    7949      7857       7885    110   
94704  4377    4377     4377      4377    4287      4283       4289    366   
94705  6011    6011     6011      6011    6011      5696       5681      9   
94706   637     637      637       637     637       637        637      1   
94707  6316    6316     6316      6316    6316      5995       5946      5   
94708  4753    4753     4753      4753    4750      4427       2597      0   
94709  2996    2996     2996      2996    2591      2830       2867     87   
94710  5109    5109     5109      5109    5109      4307       4434     86   
94720    71      71       71        71      66        71         71      9   

       lvwires  trnk  hvwires  location  latitude  obstree_he  icon_type  \
ZIP                                                                        
94702     7328  7187     7328      7328      7328        5492       7328   
94703     8241  8032     8241      8241      8241        6418       8241   
94704     4377  4365     4377      4376      4377        3022       4377   
94705     6011  6011     6011      6010      6011        4676       6011   
94706      637   637      637       637       637         486        637   
94707     6316  6313     6316      6310      6316        4915       6316   
94708     4753  4753     4753      4751      4753        3778       4753   
94709     2996  2996     2996      2994      2996        2232       2996   
94710     5109  4748     5109      5109      5109        3907       5109   
94720       71    71       71        71        71          46         71   

       stake_rmv  spread_ft  p_strip_wi  hvwirht  gps_date  growspace  \
ZIP                                                                     
94702        539       5447        5292     2299      7328       7328   
94703        654       6347        6063     2970      8241       8241   
94704        292       3002        2131     1313      4377       4377   
94705        410       4647        4632     2278      6011       6011   
94706         65        482         513      269       637        637   
94707        508       4866        5545     2454      6316       6316   
94708        123       3773        1870     1460      4753       4753   
94709        158       2208        1973      985      2996       2996   
94710        490       3854        3193     1588      5109       5109   
94720          8         45          29       23        71         71   

       height_ft  common_nam  stem_num  longitude  vert_prec  horz_prec  \
ZIP                                                                       
94702       5488        5497      5445       7328       7328       7328   
94703       6408        6424      6343       8241       8241       8241   
94704       3020        3032      3001       4377       4377       4377   
94705       4672        4719      4658       6011       6011       6011   
94706        486         486       479        637        637        637   
94707       4903        4967      4865       6316       6316       6316   
94708       3781        3948      3774       4753       4753       4753   
94709       2229        2239      2205       2996       2996       2996   
94710       3913        3927      3857       5109       5109       5109   
94720         45          45        45         71         71         71   

       rootb  condition  monosdw  siteid  swk_width  other_tree  note  \
ZIP                                                                     
94702   7328       5488     7328    7328       6553         309  5042   
94703   8238       6408     8241    8241       7567         305  6091   
94704   4373       3019     4377    4377       4099         208  3019   
94705   6010    

In [12]:
tree_count_by_zip = berkeley_trees.groupby(['ZIP']).count()

In [13]:
tree_count_by_zip

id  areaid  species  strt_nam  dbh_in  block_on  spacesize  grate  \
ZIP                                                                          
94702  7328    7328     7328      7328    6937      6956       7003     36   
94703  8241    8241     8241      8241    7949      7857       7885    110   
94704  4377    4377     4377      4377    4287      4283       4289    366   
94705  6011    6011     6011      6011    6011      5696       5681      9   
94706   637     637      637       637     637       637        637      1   
94707  6316    6316     6316      6316    6316      5995       5946      5   
94708  4753    4753     4753      4753    4750      4427       2597      0   
94709  2996    2996     2996      2996    2591      2830       2867     87   
94710  5109    5109     5109      5109    5109      4307       4434     86   
94720    71      71       71        71      66        71         71      9   

       lvwires  trnk  hvwires  location  latitude  obstree_he  icon_type  \
ZIP                                                                        
94702     7328  7187     7328      7328      7328        5492       7328   
94703     8241  8032     8241      8241      8241        6418       8241   
94704     4377  4365     4377      4376      4377        3022       4377   
94705     6011  6011     6011      6010      6011        4676       6011   
94706      637   637      637       637       637         486        637   
94707     6316  6313     6316      6310      6316        4915       6316   
94708     4753  4753     4753      4751      4753        3778       4753   
94709     2996  2996     2996      2994      2996        2232       2996   
94710     5109  4748     5109      5109      5109        3907       5109   
94720       71    71       71        71        71          46         71   

       stake_rmv  spread_ft  p_strip_wi  hvwirht  gps_date  growspace  \
ZIP                                                                     
94702        539       5447        5292     2299      7328       7328   
94703        654       6347        6063     2970      8241       8241   
94704        292       3002        2131     1313      4377       4377   
94705        410       4647        4632     2278      6011       6011   
94706         65        482         513      269       637        637   
94707        508       4866        5545     2454      6316       6316   
94708        123       3773        1870     1460      4753       4753   
94709        158       2208        1973      985      2996       2996   
94710        490       3854        3193     1588      5109       5109   
94720          8         45          29       23        71         71   

       height_ft  common_nam  stem_num  longitude  vert_prec  horz_prec  \
ZIP                                                                       
94702       5488        5497      5445       7328       7328       7328   
94703       6408        6424      6343       8241       8241       8241   
94704       3020        3032      3001       4377       4377       4377   
94705       4672        4719      4658       6011       6011       6011   
94706        486         486       479        637        637        637   
94707       4903        4967      4865       6316       6316       6316   
94708       3781        3948      3774       4753       4753       4753   
94709       2229        2239      2205       2996       2996       2996   
94710       3913        3927      3857       5109       5109       5109   
94720         45          45        45         71         71         71   

       rootb  condition  monosdw  siteid  swk_width  other_tree  note  \
ZIP                                                                     
94702   7328       5488     7328    7328       6553         309  5042   
94703   8238       6408     8241    8241       7567         305  6091   
94704   4373       3019     4377    4377       4099         208  3019   
94705   6010    

In [14]:
tree_count_by_zip = tree_count_by_zip[['id']].reset_index()

In [15]:
tree_count_by_zip.head()

ZIP    id
0  94702  7328
1  94703  8241
2  94704  4377
3  94705  6011
4  94706   637

In [16]:
tree_count_by_zip.columns = ['zip', 'count']
tree_count_by_zip

zip  count
0  94702   7328
1  94703   8241
2  94704   4377
3  94705   6011
4  94706    637
5  94707   6316
6  94708   4753
7  94709   2996
8  94710   5109
9  94720     71

In [50]:
alt.Chart(tree_count_by_zip).mark_bar().encode(
    x='zip',
    y='count'
)

alt.Chart(...)

Based on the data, the zip code with the most trees is 94703, which includes North, South and Central Berkeley and the zip code with the least amount of trees is 94720 which includes parts of the UC Berkeley campus and Southside, however, I am sure that UC Berkeley has its own tree dataset. The second lowest zip code is 94706, which includes Albany, which is quite surprising. 

## Get Tree Density

How evenly spread out are the trees in Berkeley or are they denser in certain communities?

In [17]:
zip_codes = pd.read_csv('berkeley_zip_codes.csv', dtype={'ZIP': object})

In [18]:
zip_codes

ZIP  POP2007  POP07_SQMI  SQMI
0  94702    15601     12893.4  1.21
1  94703    20297     15034.8  1.35
2  94704    20282      9054.5  2.24
3  94705    12224      6301.0  1.94
4  94706    16074     12270.2  1.31
5  94707    12110      6920.0  1.75
6  94708    11217      3348.4  3.35
7  94709    10476     18707.1  0.56
8  94710     8324      3005.1  2.77
9  94720     1022      1439.4  0.71

In [19]:
tree_stats_by_zip = pd.merge(
    tree_count_by_zip,
    zip_codes,
    left_on='zip',
    right_on='ZIP',
    how='outer',
    validate='1:1',
)

In [20]:
tree_stats_by_zip

zip  count    ZIP  POP2007  POP07_SQMI  SQMI
0  94702   7328  94702    15601     12893.4  1.21
1  94703   8241  94703    20297     15034.8  1.35
2  94704   4377  94704    20282      9054.5  2.24
3  94705   6011  94705    12224      6301.0  1.94
4  94706    637  94706    16074     12270.2  1.31
5  94707   6316  94707    12110      6920.0  1.75
6  94708   4753  94708    11217      3348.4  3.35
7  94709   2996  94709    10476     18707.1  0.56
8  94710   5109  94710     8324      3005.1  2.77
9  94720     71  94720     1022      1439.4  0.71

In [21]:
tree_stats_by_zip['count_by_sqmi'] = tree_stats_by_zip['count'] / tree_stats_by_zip['SQMI'] 
tree_stats_by_zip

zip  count    ZIP  POP2007  POP07_SQMI  SQMI  count_by_sqmi
0  94702   7328  94702    15601     12893.4  1.21    6056.198347
1  94703   8241  94703    20297     15034.8  1.35    6104.444444
2  94704   4377  94704    20282      9054.5  2.24    1954.017857
3  94705   6011  94705    12224      6301.0  1.94    3098.453608
4  94706    637  94706    16074     12270.2  1.31     486.259542
5  94707   6316  94707    12110      6920.0  1.75    3609.142857
6  94708   4753  94708    11217      3348.4  3.35    1418.805970
7  94709   2996  94709    10476     18707.1  0.56    5350.000000
8  94710   5109  94710     8324      3005.1  2.77    1844.404332
9  94720     71  94720     1022      1439.4  0.71     100.000000

In [22]:
tree_stats_by_zip.sort_values(by=['count_by_sqmi'], ascending=False)

zip  count    ZIP  POP2007  POP07_SQMI  SQMI  count_by_sqmi
1  94703   8241  94703    20297     15034.8  1.35    6104.444444
0  94702   7328  94702    15601     12893.4  1.21    6056.198347
7  94709   2996  94709    10476     18707.1  0.56    5350.000000
5  94707   6316  94707    12110      6920.0  1.75    3609.142857
3  94705   6011  94705    12224      6301.0  1.94    3098.453608
2  94704   4377  94704    20282      9054.5  2.24    1954.017857
8  94710   5109  94710     8324      3005.1  2.77    1844.404332
6  94708   4753  94708    11217      3348.4  3.35    1418.805970
4  94706    637  94706    16074     12270.2  1.31     486.259542
9  94720     71  94720     1022      1439.4  0.71     100.000000

In [51]:
alt.Chart(tree_stats_by_zip).mark_bar().encode(
    x='zip',
    y='count_by_sqmi'
)

alt.Chart(...)

Based on my observation, it looks like zip codes 94703 and 94702 have the highest tree density per square mile while zip codes 94720 and 94706 have the least tree density per square mile. In further analysis, it would be interesting to see how the count by square mile changes after 2014. 

## Get Most Common Trees

What are the most common trees in Berkeley? Where are they most likely situated?

In [23]:
berkeley_trees

id  areaid                  species         strt_nam  dbh_in  \
0          0       3        Prunus cerasifera       COLUSA AVE    13.0   
1          1       3  Liquidambar styraciflua       COLUSA AVE     7.5   
2          2       3            Planting Site       BEVERLY PL     0.0   
3          3       3            Planting Site       BEVERLY PL     0.0   
4          4       3            Acer  species       BEVERLY PL     1.0   
...      ...     ...                      ...              ...     ...   
46032  46032       7  Liriodendron tulipifera  M L KING JR WAY    16.0   
46033  46033       7  Liriodendron tulipifera   UNIVERSITY AVE    15.0   
46034  46034       7            Planting Site   UNIVERSITY AVE     0.0   
46035  46035       7  Liriodendron tulipifera   UNIVERSITY AVE    16.0   
46036  46036       7  Liriodendron tulipifera   UNIVERSITY AVE    14.0   

              block_on  spacesize grate lvwires trnk hvwires location  \
0           BEVERLY PL        3.5   NaN       Y    N       Y     LEFT   
1           BEVERLY PL        3.5   NaN       Y    N       Y     LEFT   
2           BEVERLY PL        3.5   NaN       Y    N       Y    FRONT   
3           BEVERLY PL        3.5   NaN       Y    N       Y    FRONT   
4           BEVERLY PL        3.5   NaN       Y    N       Y    FRONT   
...                ...        ...   ...     ...  ...     ...      ...   
46032  M L KING JR WAY        4.0   NaN       N    N       N    FRONT   
46033   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   
46034   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   
46035   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   
46036   UNIVERSITY AVE        4.0   NaN       N    N       N    FRONT   

        latitude  obstree_he icon_type stake_rmv  spread_ft  p_strip_wi  \
0      37.884954         2.0         T       NaN       18.0         4.0   
1      37.884965         3.0         T       NaN       24.0         4.0   
2      37.884892         NaN         P       NaN        NaN         4.0   
3      37.884873         NaN         P       NaN        NaN         4.0   
4      37.884855         3.0         T       NaN        6.0         4.0   
...          ...         ...       ...       ...        ...         ...   
46032  37.871332         3.0         T       NaN       21.0         NaN   
46033  37.871171         3.0         T       NaN       21.0         NaN   
46034  37.871238         NaN         P       NaN        NaN         NaN   
46035  37.871154         3.0         T       NaN       27.0         NaN   
46036  37.871134         3.0         T       NaN       24.0         NaN   

       hvwirht                   gps_date      growspace  height_ft  \
0         40.0  2012-10-01T07:00:00+00:00      TREE LAWN       30.0   
1         40.0  2012-10-01T07:00:00+00:00      TREE LAWN       35.0   
2         40.0  2012-10-01T07:00:00+00:00  PLANTING SITE        NaN   
3         40.0  2012-10-01T07:00:00+00:00  PLANTING SITE        NaN   
4         40.0  2012-10-01T07:00:00+00:00      TREE LAWN       10.0   
...        ...                        ...            ...        ...   
46032      NaN  2012-12-06T08:00:00+00:00           WELL       50.0   
46033      NaN  2012-12-06T08:00:00+00:00           WELL       50.0   
46034      NaN  2012-12-06T08:00:00+00:00  PLANTING SITE        NaN   
46035      NaN  2012-12-06T08:00:00+00:00           WELL       55.0   
46036      NaN  2012-12-06T08:00:00+00:00           WELL       35.0   

        common_nam  stem_num   longitude  vert_prec  horz_prec rootb  \
0      Cherry plum       1.0 -122.278251        0.1        0.1     N   
1         Sweetgum       1.0 -122.278166        0.5        0.4     N   
2              NaN       NaN -122.278032        0.1        0.1     N   
3              NaN       NaN -122.277953        0.1        0.1     N   
4            Maple       1.0 -122.277879        0.1        0.1     N   
...            ...       ...         ...        ...       

In [24]:
berkeley_tree_species = berkeley_trees.groupby(['species']).count()

In [25]:
berkeley_tree_species

id  areaid  strt_nam  dbh_in  block_on  \
species                                                                
Abies  species                15      15        15      15        15   
Acacia baileyana              10      10        10      10        10   
Acacia dealbata               15      15        15      15        14   
Acacia longifolia              3       3         3       3         3   
Acacia melanoxylon           242     242       242     242       145   
...                          ...     ...       ...     ...       ...   
Washingtonia robusta          98      98        98      98        97   
Yucca aloifolia                1       1         1       1         1   
Yucca gloriosa                84      84        84      84        84   
Zelkova serrata              126     126       126     126       126   
x Cupressocyparis leylandii   18      18        18      18        17   

                             spacesize  grate  lvwires  trnk  hvwires  \
species                                                                 
Abies  species                       8      0       15    15       15   
Acacia baileyana                    10      0       10    10       10   
Acacia dealbata                      8      0       15    15       15   
Acacia longifolia                    3      0        3     3        3   
Acacia melanoxylon                 133      1      242   242      242   
...                                ...    ...      ...   ...      ...   
Washingtonia robusta                96      0       98    98       98   
Yucca aloifolia                      1      0        1     1        1   
Yucca gloriosa                      82      0       84    84       84   
Zelkova serrata                    122      0      126   126      126   
x Cupressocyparis leylandii          9      0       18    18       18   

                             location  latitude  obstree_he  icon_type  \
species                                                                  
Abies  species                     15        15          15         15   
Acacia baileyana                   10        10          10         10   
Acacia dealbata                    15        15          15         15   
Acacia longifolia                   3         3           3          3   
Acacia melanoxylon                242       242         240        242   
...                               ...       ...         ...        ...   
Washingtonia robusta               98        98          98         98   
Yucca aloifolia                     1         1           1          1   
Yucca gloriosa                     84        84          84         84   
Zelkova serrata                   125       126         126        126   
x Cupressocyparis leylandii        18        18          18         18   

                             stake_rmv  spread_ft  p_strip_wi  hvwirht  \
species                                                                  
Abies  species                       0         15           5        5   
Acacia baileyana                     1         10           7        3   
Acacia dealbata                      0         15           7        1   
Acacia longifolia                    0          3           3        0   
Acacia melanoxylon                   0        240         119       67   
...                                ...        ...         ...      ...   
Washingtonia robusta                 0         98          83        7   
Yucca aloifolia                      0          1           1        1   
Yucca gloriosa                       1         84          79       35   
Zelkova serrata                     12        126          80       42   
x Cupressocyparis leylandii          0         18           7        2   

                             gps_date  growspace  height_ft  common_nam  \
species                                                                   
Abies  species                     15         15         15        

In [26]:
berkeley_tree_species = berkeley_tree_species[['id']].reset_index()

In [27]:
berkeley_tree_species.head()

species   id
0      Abies  species   15
1    Acacia baileyana   10
2     Acacia dealbata   15
3   Acacia longifolia    3
4  Acacia melanoxylon  242

In [28]:
berkeley_tree_species.tail()

species   id
262         Washingtonia robusta   98
263              Yucca aloifolia    1
264               Yucca gloriosa   84
265              Zelkova serrata  126
266  x Cupressocyparis leylandii   18

In [29]:
berkeley_tree_species.columns = ['species', 'count']
berkeley_tree_species

species  count
0                 Abies  species     15
1               Acacia baileyana     10
2                Acacia dealbata     15
3              Acacia longifolia      3
4             Acacia melanoxylon    242
..                           ...    ...
262         Washingtonia robusta     98
263              Yucca aloifolia      1
264               Yucca gloriosa     84
265              Zelkova serrata    126
266  x Cupressocyparis leylandii     18

[267 rows x 2 columns]

In [30]:
berkeley_tree_species.sort_values(by=['count'], ascending=False)

species  count
189            Planting Site  10620
190         Platanus hybrida   3208
136  Liquidambar styraciflua   2139
203        Prunus cerasifera   1864
216        Quercus agrifolia   1751
..                       ...    ...
243    Tabebuia impetiginosa      1
34           Brahea  species      1
121          Juglans species      1
227    Rhododendron  species      1
46         Camellia japonica      1

[267 rows x 2 columns]

In [52]:
alt.Chart(berkeley_tree_species).mark_bar().encode(
    x='species',
    y='count'
)

alt.Chart(...)

Based on my observation, it looks like the species `Platanus hybrid` is the most common species in Berkeley. Based on the City's website, it looks like `Planting site` refers to trees that will be potentially planted, which requires city approval.

### Most Common Trees by Zip Code

What are the most common trees in Berkeley? Where are they most likely situated?

In [31]:
berkeley_tree_species_by_zip = berkeley_trees.groupby(['ZIP', 'species']).count()

In [32]:
berkeley_tree_species_by_zip = berkeley_tree_species_by_zip[['id']].reset_index()

In [33]:
berkeley_tree_species_by_zip

ZIP                species  id
0     94702       Acacia baileyana   5
1     94702      Acacia longifolia   1
2     94702     Acacia melanoxylon  13
3     94702          Acer  species   3
4     94702      Acer buergerianum  94
...     ...                    ...  ..
1383  94720   Robinia pseudoacacia   5
1384  94720  Tristaniopsis laurina   3
1385  94720        Ulmus americana   1
1386  94720       Ulmus parvifolia   6
1387  94720        Zelkova serrata   1

[1388 rows x 3 columns]

In [34]:
# rename `id` to `count`
berkeley_tree_species_by_zip.rename(columns={'id': 'count'}, inplace=True)

In [35]:
# Get top species in 94702
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94702'].sort_values(by=['count'], ascending=False).head()

ZIP             species  count
116  94702       Planting Site   1831
117  94702    Platanus hybrida    376
111  94702  Pistacia chinensis    361
135  94702    Pyrus calleryana    284
137  94702     Pyrus kawakamii    247

In [36]:
# Get top species in 94703
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94703'].sort_values(by=['count'], ascending=False).head()

ZIP                  species  count
294  94703            Planting Site   1817
261  94703  Liquidambar styraciflua    506
305  94703        Prunus cerasifera    339
295  94703         Platanus hybrida    303
290  94703       Pistacia chinensis    258

In [37]:
# Get top species in 94704
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94704'].sort_values(by=['count'], ascending=False).head()

ZIP                  species  count
446  94704            Planting Site   1345
417  94704  Liquidambar styraciflua    353
447  94704         Platanus hybrida    205
360  94704              Acer rubrum    181
445  94704    Pittosporum undulatum    147

In [38]:
# Get top species in 94705
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94705'].sort_values(by=['count'], ascending=False).head()

ZIP                  species  count
605  94705            Planting Site   1292
606  94705         Platanus hybrida    486
574  94705  Liquidambar styraciflua    458
614  94705        Prunus cerasifera    246
500  94705              Acer rubrum    219

In [39]:
# Get top species in 94706
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94706'].sort_values(by=['count'], ascending=False).head()

ZIP                  species  count
709  94706            Planting Site    151
706  94706       Pistacia chinensis     46
720  94706         Pyrus calleryana     44
696  94706  Liquidambar styraciflua     31
661  94706            Acer palmatum     27

In [40]:
# Get top species in 94707
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94707'].sort_values(by=['count'], ascending=False).head()

ZIP              species  count
856  94707        Planting Site   1349
857  94707     Platanus hybrida    568
877  94707    Quercus agrifolia    470
867  94707    Prunus cerasifera    445
775  94707  Cinnamomum camphora    432

In [41]:
# Get top species in 94708
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94708'].sort_values(by=['count'], ascending=False).head()

ZIP               species  count
1027  94708         Planting Site    805
1047  94708     Quercus agrifolia    724
1035  94708     Prunus cerasifera    342
1060  94708  Sequoia sempervirens    213
1028  94708      Platanus hybrida    209

In [42]:
# Get top species in 94709
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94709'].sort_values(by=['count'], ascending=False).head()

ZIP                  species  count
1174  94709            Planting Site    757
1175  94709         Platanus hybrida    208
1142  94709  Liquidambar styraciflua    199
1193  94709        Quercus agrifolia    147
1182  94709        Prunus cerasifera    112

In [43]:
# Get top species in 94710
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94710'].sort_values(by=['count'], ascending=False).head()

ZIP               species  count
1325  94710         Planting Site   1182
1326  94710      Platanus hybrida    801
1339  94710      Pyrus calleryana    202
1261  94710  Cupressus macrocarpa    186
1225  94710           Acer rubrum    169

In [44]:
# Get top species in 94720
berkeley_tree_species_by_zip[berkeley_tree_species_by_zip['ZIP'] == '94720'].sort_values(by=['count'], ascending=False).head()

ZIP                  species  count
1379  94720            Planting Site     26
1378  94720       Pistacia chinensis      7
1386  94720         Ulmus parvifolia      6
1375  94720    Gleditsia triacanthos      5
1376  94720  Liquidambar styraciflua      5

Observations:

- 94702: The most popular tree is the `Platanus hybrida`
- 94703: The most popular tree is the `Liquidambar styraciflua`	
- 94704: The most popular tree is the `Liquidambar styraciflua`
- 94705: The most popular tree is the `Platanus hybrida`	
- 94706: The most popular tree is the `Pistacia chinensis`
- 94707: The most popular tree is the `Platanus hybrida`
- 94708: The most popular tree is the `Quercus agrifolia`
- 94709: The most popular tree is the `Platanus hybrida`
- 94710: The most popular tree is the `Platanus hybrida`
- 94720: The most popular tree is the `Pistacia chinensis`

Based on the data, it looks like the most popular tree is the `Platanus hybrida` and the second-most popular trees are the `Pistacia chinensis` and the `Liquidambar styraciflua`. 

## Extra notes

The last two questions ask if there is way to find the age and condition of the tree, the best way to analyze this would be to sort through the notes at the end of each row. In order to isolate the zip code and the corresponding notes, we created a CSV.

In [45]:
notes = berkeley_trees[['ZIP','note']].dropna().sort_values(by=['note'])

In [46]:
notes

ZIP                                               note
25096  94705                        "staked" to acacia, crowded
20023  94705  'female'  curved trunk, lean towards the road,...
16729  94707  'needs to be brace', trunk craked, trunk wound...
14246  94707                                           1 branch
39026  94703  1 foot from utility and sign - move sign, codo...
...      ...                                                ...
15184  94707                                 wounds on scaffold
17105  94707                                      yellow fronds
11193  94708                             yucca grove, under fir
9867   94703                                  zip ties on trunk
41316  94703                                  zip ties on trunk

[33882 rows x 2 columns]

In [47]:
notes.to_csv('notes.csv', index=False)

I opened notes.csv and noticed that there were several mentions of `stumps` and `deadwood`, which shows that trees were either cut down or have parts of the tree that are dying. 

There are several keywords to specify a dying tree throughout the csv so it would require a lot of sifting through the data to ensure every tree is counted. 

There are also many different keywords that city uses to specify the tree condition, it would be interesting to identify what these terms are to further explore the specifics of this data.

Considering this dataset only covers 2014 data, it would also be interesting to see how this tree data has changed over time and if more trees have been planted or removed.
